server:
  port: 8380

spring:
  application:
    name: e-commerce
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Fen?currentSchema=ecommerce&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: postgres
    #schema: classpath:schema.sql
    initialization-mode: always
    hikari:
      maximum-pool-sie: 20
      connectionTimeout: 2000
      poolName: ecommerce-hikari-postgres-cp
      maxLifetime: 1100000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG